/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;
import java.io.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author FILIPUSMANIK
 */
public class CRUD_amplang extends javax.swing.JFrame {

    /**
     * Creates new form CRUD
     */
    public CRUD_amplang() {
        initComponents();
        table();
        this.path_txt.setVisible(false);
        this.btn_edit.setVisible(false);
        this.btn_hapus.setVisible(false);
    }
    private void table(){
        DefaultTableModel tbl  = (DefaultTableModel) tabel_amplang.getModel();
        tabel_amplang.setRowHeight(40);
        tabel_amplang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        

//        data_anime.getColumnModel().removeColumn(data_anime.getColumnModel().getColumn(6));
//        data_anime.getColumnModel().removeColumn(data_anime.getColumnModel().getColumn(6));
        
        tbl.setRowCount(0);        
        try{
            Connection conn = Koneksi.getConnection();
            // membuat statement dan mengirimkan query ke database
            String sql = "SELECT * FROM tb_amplangs";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            // mengisi data dari ResultSet ke dalam model
            while(rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama");
                int harga = rs.getInt("harga");
                String jenis = rs.getString("jenis");
                String level = rs.getString("level");
                String foto = rs.getString("foto");
                tbl.addRow(new Object []{id, nama, harga, jenis, level, foto});
                tabel_amplang.setModel(tbl);
            }
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "There is an error : " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void cls(){
        this.txt_harga.setText("");
        this.txt_nama.setText("");
        this.combo_level.setSelectedIndex(-1);
        this.path_txt.setText("");
        this.label_foto.setIcon(null);
        this.rb_amplang_ayam.setSelected(false);
        this.rb_amplang_daging.setSelected(false);
        this.rb_amplang_ikan.setSelected(false);
        txt_nama.requestFocusInWindow();
        tabel_amplang.clearSelection();
        this.btn_tambah.setVisible(true);
        this.btn_edit.setVisible(false);
        this.btn_hapus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        rb_amplang_daging = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb_amplang_ikan = new javax.swing.JRadioButton();
        rb_amplang_ayam = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        combo_level = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        label_foto = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_browse = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        path_txt = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_amplang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HALAMAN CRUD AMPLANG");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HARGA");

        rb_amplang_daging.setText("Amplang daging");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Jenis");

        rb_amplang_ikan.setText("Amplang ikan");

        rb_amplang_ayam.setText("Amplang ayam");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FOTO AMPLANG");

        combo_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3", "Level 4", "Level Max" }));
        combo_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_levelActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LEVEL PEDAS");

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_browse.setBackground(new java.awt.Color(0, 0, 255));
        btn_browse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_browse.setForeground(new java.awt.Color(255, 255, 255));
        btn_browse.setText("PILIH FOTO");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(0, 0, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(0, 0, 255));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        path_txt.setText("jLabel7");

        btn_kembali.setBackground(new java.awt.Color(0, 0, 204));
        btn_kembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setIcon(new javax.swing.ImageIcon("C:\\Praktikum_PBO\\Tugas Pak Putut\\UAS\\gambar\\icons8-left-arrow-50.png")); // NOI18N
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn_browse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_amplang_ayam)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rb_amplang_daging)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_level, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(label_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(path_txt))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rb_amplang_ikan)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btn_kembali))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nama)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_harga)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_amplang_ikan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_amplang_daging)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_amplang_ayam))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(combo_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(path_txt)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_browse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabel_amplang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "harga", "jenis", "level", "foto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_amplang.setGridColor(new java.awt.Color(0, 0, 0));
        tabel_amplang.setShowGrid(true);
        tabel_amplang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_amplangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_amplang);
        if (tabel_amplang.getColumnModel().getColumnCount() > 0) {
            tabel_amplang.getColumnModel().getColumn(5).setMinWidth(0);
            tabel_amplang.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_levelActionPerformed

    }//GEN-LAST:event_combo_levelActionPerformed

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
        JFileChooser pilihfile = new JFileChooser();
        int returnValue = pilihfile.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File pathfile = pilihfile.getSelectedFile();
            ImageIcon icon = new ImageIcon(pathfile.toString());
            path_txt.setText(pathfile.getAbsolutePath());
            Image img = icon.getImage().getScaledInstance(label_foto.getWidth(), label_foto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            label_foto.setIcon(ic);
        }
    }//GEN-LAST:event_btn_browseActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed

        Home halaman_utama = new Home();
        this.dispose();
        halaman_utama.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String hargatext = this.txt_harga.getText();
        int harga = Integer.parseInt(hargatext);
        String levelPedas = combo_level.getSelectedItem().toString();
        try{
            Connection conn = Koneksi.getConnection();
            String sql = "insert into tb_amplangs (nama, harga, jenis, level, foto) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, this.txt_nama.getText());
            stmt.setInt(2, harga);
            if(this.rb_amplang_ayam.isSelected()){
                String jenis = "Amplang ayam";
                stmt.setString(3, jenis);
            } else if (this.rb_amplang_daging.isSelected()){
                String jenis = "Amplang daging";
                stmt.setString(3, jenis);
            } else if (this.rb_amplang_ikan.isSelected()){
                String jenis = "Amplang ikan";
                stmt.setString(3, jenis);
            }
            stmt.setString(4, levelPedas);
            stmt.setString(5, this.path_txt.getText());
            int masukan_row = stmt.executeUpdate();
            if (masukan_row > 0 ){
                cls();
                JOptionPane.showMessageDialog(this, "Data Successfully Added!!! ", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                table();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "There is an error : " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void tabel_amplangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_amplangMouseClicked
        this.btn_tambah.setVisible(false);
        this.btn_edit.setVisible(true);
        this.btn_hapus.setVisible(true);
        int baris = tabel_amplang.getSelectedRow();
        this.txt_nama.setText(tabel_amplang.getValueAt(baris, 1).toString()); // nama
        this.txt_harga.setText(tabel_amplang.getValueAt(baris, 2).toString()); // harga
        String jenis_amplang = (String) tabel_amplang.getValueAt(baris, 3).toString();
        if (jenis_amplang.equals("Amplang ayam") ) {
            this.rb_amplang_ayam.setSelected(true);
        }else if(jenis_amplang.equals("Amplang daging")){
            this.rb_amplang_daging.setSelected(true);
        } else if(jenis_amplang.equals("Amplang ikan")) {
            this.rb_amplang_ikan.setSelected(true);
        }
        String level_amplang = (String)tabel_amplang.getValueAt(baris, 4).toString();
        this.combo_level.setSelectedItem(level_amplang);
        this.path_txt.setText(tabel_amplang.getValueAt(baris, 5).toString()); // foto\
        String path = (String) tabel_amplang.getValueAt(baris, 5).toString();
        ImageIcon icn = new ImageIcon(path);
        Image img = icn.getImage().getScaledInstance(label_foto.getWidth(), label_foto.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon ic = new ImageIcon(img);
        label_foto.setIcon(ic);
    }//GEN-LAST:event_tabel_amplangMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int baris = tabel_amplang.getSelectedRow();
        int option = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menyimpan perubahan ini ???", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            Connection conn = Koneksi.getConnection();
            String hargatext = this.txt_harga.getText();
            int harga = Integer.parseInt(hargatext);
            String levelPedas = combo_level.getSelectedItem().toString();
            String sql = "UPDATE tb_amplang SET nama=?, harga=?, jenis=?, level=?, foto=? WHERE id=?";
            try {
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, this.txt_nama.getText());
                stmt.setInt(2, harga);
                if(this.rb_amplang_ayam.isSelected()){
                    String jenis = "Amplang ayam";
                    stmt.setString(3, jenis);
                } else if (this.rb_amplang_daging.isSelected()){
                    String jenis = "Amplang daging";
                    stmt.setString(3, jenis);
                } else if (this.rb_amplang_ikan.isSelected()){
                    String jenis = "Amplang ikan";
                    stmt.setString(3, jenis);
                }
                stmt.setString(4, levelPedas);
                stmt.setString(5, this.path_txt.getText());
                stmt.setString(6, tabel_amplang.getValueAt(baris, 0).toString());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Successfully Updated!!! ", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                cls();
                table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "There is an error : " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Updated data Canceled!!! ", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
            cls();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int baris = tabel_amplang.getSelectedRow();
        Connection conn = Koneksi.getConnection();
        int option = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menyimpan perubahan ini ???", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM tb_amplang WHERE id=?";
            try {
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, tabel_amplang.getValueAt(baris, 0).toString());                
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Successfully deleted !!! ", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                cls();
                table();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "There is an error : " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
            }
        }  else {
            JOptionPane.showMessageDialog(this, "Deleted data Canceled!!! ", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
            cls();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_amplang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_amplang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_amplang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_amplang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_amplang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> combo_level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_foto;
    private javax.swing.JLabel path_txt;
    private javax.swing.JRadioButton rb_amplang_ayam;
    private javax.swing.JRadioButton rb_amplang_daging;
    private javax.swing.JRadioButton rb_amplang_ikan;
    private javax.swing.JTable tabel_amplang;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
