/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.util.Set;
import javax.swing.table.*;

/**
 *
 * @author FILIPUSMANIK
 */
public class halaman_pemesanan extends javax.swing.JFrame {
    
    public String nama;
    public String harga;
    public String jenis;
    public String level;
    public String foto;
    
    
    public ImageIcon getIcon(){
        return (ImageIcon) label_fotos.getIcon();
    }
    /**
     * Creates new form
     */
    public halaman_pemesanan() {
        initComponents();
        table();
    }
    
    private void table(){
        DefaultTableModel tbl  = (DefaultTableModel) tabel_amplangs.getModel();
        tabel_amplangs.setRowHeight(40);
        tabel_amplangs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableColumnModel model_tabel = tabel_amplangs.getColumnModel();
        TableColumn column = model_tabel.getColumn(0);
        TableColumn column_5 = model_tabel.getColumn(5);
//        column.setMinWidth(0);
//        column.setMaxWidth(0);                
//        column_5.setMinWidth(0);
//        column_5.setMaxWidth(0);        
        tbl.setRowCount(0);        
        try{
            Connection conn = Koneksi.getConnection();
            // membuat statement dan mengirimkan query ke database
            String sql = "SELECT * FROM tb_amplangs";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            // mengisi data dari ResultSet ke dalam model
            while(rs.next()) {
                int id = rs.getInt("id");
                String namas = rs.getString("nama");
                String hargas = String.valueOf(rs.getInt("harga"));
                String jeniss = rs.getString("jenis");
                String levels = rs.getString("level");
                String fotos = rs.getString("foto");
                tbl.addRow(new Object []{id, namas, hargas, jeniss, levels, fotos});
                tabel_amplangs.setModel(tbl);
            }
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "There is an error : " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void tabel_cari(){
        String keyword = cari_txt.getText();
        DefaultTableModel tbl  = (DefaultTableModel) tabel_amplangs.getModel();
        tabel_amplangs.setRowHeight(40);
        tabel_amplangs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableColumnModel model_tabel = tabel_amplangs.getColumnModel();
        TableColumn column = model_tabel.getColumn(0);
        TableColumn column_5 = model_tabel.getColumn(5);
//        column.setMinWidth(0);
//        column.setMaxWidth(0);                
//        column_5.setMinWidth(0);
//        column_5.setMaxWidth(0);        
        tbl.setRowCount(0);        
        try{
            Connection conn = Koneksi.getConnection();
            // membuat statement dan mengirimkan query ke database
            String sql = "SELECT * FROM tb_amplangs WHERE nama LIKE '%" + keyword + "%'";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            // mengisi data dari ResultSet ke dalam model
            while(rs.next()) {
                int id = rs.getInt("id");
                String namas = rs.getString("nama");
                String hargas = String.valueOf(rs.getInt("harga"));
                String jeniss = rs.getString("jenis");
                String levels = rs.getString("level");
                String fotos = rs.getString("foto");
                tbl.addRow(new Object []{id, namas, hargas, jeniss, levels, fotos});
                tabel_amplangs.setModel(tbl);
            }
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "There is an error : " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_desc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_amplangs = new javax.swing.JTable();
        cari_txt = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        label_fotos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HALAMAN UTAMA AMPLANG");

        btn_desc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desc.setText("DESCRIPTION");
        btn_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descActionPerformed(evt);
            }
        });

        tabel_amplangs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "harga", "jenis", "level", "foto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_amplangs.setGridColor(new java.awt.Color(0, 0, 0));
        tabel_amplangs.setShowGrid(true);
        tabel_amplangs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_amplangsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_amplangs);

        cari_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_cari.setIcon(new javax.swing.ImageIcon("C:\\Praktikum_PBO\\Tugas Pak Putut\\UAS\\gambar\\icons8-search-24.png")); // NOI18N
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setIcon(new javax.swing.ImageIcon("C:\\Praktikum_PBO\\Tugas Pak Putut\\UAS\\gambar\\icons8-left-arrow-50.png")); // NOI18N
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_kembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(cari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(label_fotos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btn_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari_txt)))
                    .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(label_fotos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        login halaman_login = new login();
        this.dispose();
        halaman_login.setVisible(true);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descActionPerformed
        ImageIcon icon = (ImageIcon) label_fotos.getIcon();
        desc_form deskripsi = new desc_form();
        deskripsi.setNama(nama);
        deskripsi.setHarga(harga);
        deskripsi.setJenis(jenis);
        deskripsi.setLevel(level);
        deskripsi.setFoto(icon);
        this.dispose();
        deskripsi.setVisible(true);
    }//GEN-LAST:event_btn_descActionPerformed

    private void tabel_amplangsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_amplangsMouseClicked
        int baris = tabel_amplangs.getSelectedRow();
        nama =  (String) tabel_amplangs.getValueAt(baris, 1).toString();
        harga = (String) tabel_amplangs.getValueAt(baris, 2).toString();
        jenis = (String)  tabel_amplangs.getValueAt(baris, 3).toString();
        level = (String)  tabel_amplangs.getValueAt(baris, 4).toString();
        String path = (String) tabel_amplangs.getValueAt(baris, 5).toString();
        ImageIcon icn = new ImageIcon(path);
        Image img = icn.getImage().getScaledInstance(label_fotos.getWidth(), label_fotos.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon ic = new ImageIcon(img);
        label_fotos.setIcon(ic);
    }//GEN-LAST:event_tabel_amplangsMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        tabel_cari();
    }//GEN-LAST:event_btn_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_desc;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JTextField cari_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fotos;
    private javax.swing.JTable tabel_amplangs;
    // End of variables declaration//GEN-END:variables
}
